# Generated by Django 5.0.6 on 2025-08-19 22:58

import apps.scans.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.CharField(default=apps.scans.models.generate_uuid, max_length=30, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('DUPLICATE', 'Duplicate'), ('ERROR', 'Error')], default='SUCCESS', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='events.event')),
            ],
            options={
                'verbose_name': 'Scan Log',
                'verbose_name_plural': 'Scan Logs',
                'db_table': 'scan_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
