# Generated by Django 5.0.6 on 2025-08-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='is_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='last_scan_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='override_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('DUPLICATE', 'Duplicate'), ('DUPLICATE_OVERRIDE', 'Duplicate Override'), ('ERROR', 'Error')], default='SUCCESS', max_length=20),
        ),
    ]
