# Generated by Django 5.0.6 on 2025-08-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duplicate_policy',
            field=models.CharField(choices=[('ONCE_PER_EVENT', 'Once per event'), ('ONCE_PER_DAY', 'Once per day'), ('ALLOW_DUPLICATES', 'Allow duplicates')], default='ONCE_PER_EVENT', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_permanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
